name: protestnews
channels:
    - conda-forge
    - pytorch
dependencies:
    - click=7.1.2
    - datasets=1.2.1
    - gputil=1.4.0
    - matplotlib=3.3.4
    - mlflow=1.14.1
    - pandas=1.1.3
    - pip
    - plotly = 4.14.3
    - pytest=6.2.2
    - seaborn=0.11.1
    - scikit-learn=0.24.1
    - pip:
        - hyperopt
        - ray[tune]==1.2.0
        - transformers[torch]==4.4.2
        - seqeval
        - -e .


