name: protestnews
channels:
    - conda-forge
    - pytorch
dependencies:
    - click=7.1.2
    - matplotlib=3.3.4
    - cudatoolkit=10.2
    - datasets=1.2.1
    - gputil=1.4.0
    - mlflow=1.14.1
    - pandas=1.1.3
    - pip
    - plotly = 4.14.3
    - pytest=6.2.2
    - pytorch=1.7.1=py3.6_cuda10.2.89_cudnn7.6.5_0
    - ray-tune=1.1.0
    - scikit-learn=0.24.1
    - seaborn=0.11.1
    - torchaudio=0.7.2
    - torchvision=0.8.2
    - transformers=4.4.2
    - pip:
        - hyperopt
        - ray[tune]==1.2.0
        - seqeval
        - -e .